---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hobisede/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
